
wordpress:
    image: wordpress
    env_file:
    - wp-variables.env
    links:
     - mariadb:mysql
    ports:
     - 8080:80
    volumes:
     - ./code:/code
     - ./html:/var/www/html
mariadb:
    image: mariadb
    env_file:
    - wp-variables.env
    volumes:
     - ./database:/var/lib/mysql
